require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  Exclude:
    - sandbox/**/*
    - spec/dummy/**/*
    - vendor/bundle/**/*

RSpec/DescribeClass:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
    - db/migrate/**/*
    - bin/**/*

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
